algoritmo "semnome"
var
   X, Y : Inteiro
Procedimento Soma (var A, B: Inteiro)
Inicio
      A <- A + 1
      B <- B + 2
      EscrevaL (" O Valor de A = ", A )
      EscrevaL (" O Valor de B = ", B)
      EscrevaL (" A Soma A + B = ", A+B)
FimProcedimento
inicio
      X <- 4
      y <- 8
      Soma (X, Y)
      EscrevaL ("O Valor de x= ", X)
      EscrevaL ("O Valor de y= ", Y)
      
fimalgoritmo